/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './+__root'
import { Route as StationsRouteImport } from './+stations'
import { Route as SettingsRouteImport } from './+settings'
import { Route as SearchRouteImport } from './+search'
import { Route as HistoryRouteImport } from './+history'
import { Route as GenresRouteImport } from './+genres'
import { Route as BookmarksRouteImport } from './+bookmarks'
import { Route as IndexRouteImport } from './+index'
import { Route as StationTokenRouteImport } from './+station.$token'
import { Route as PlaylistPlaylistIdRouteImport } from './+playlist.$playlistId'
import { Route as AlbumAlbumIdRouteImport } from './+album.$albumId'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationTokenRoute = StationTokenRouteImport.update({
  id: '/station/$token',
  path: '/station/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/genres': typeof GenresRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/station/$token': typeof StationTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/genres': typeof GenresRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/station/$token': typeof StationTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/genres': typeof GenresRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/station/$token': typeof StationTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/genres'
    | '/history'
    | '/search'
    | '/settings'
    | '/stations'
    | '/album/$albumId'
    | '/playlist/$playlistId'
    | '/station/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/genres'
    | '/history'
    | '/search'
    | '/settings'
    | '/stations'
    | '/album/$albumId'
    | '/playlist/$playlistId'
    | '/station/$token'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/genres'
    | '/history'
    | '/search'
    | '/settings'
    | '/stations'
    | '/album/$albumId'
    | '/playlist/$playlistId'
    | '/station/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  GenresRoute: typeof GenresRoute
  HistoryRoute: typeof HistoryRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StationsRoute: typeof StationsRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  StationTokenRoute: typeof StationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$token': {
      id: '/station/$token'
      path: '/station/$token'
      fullPath: '/station/$token'
      preLoaderRoute: typeof StationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  GenresRoute: GenresRoute,
  HistoryRoute: HistoryRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StationsRoute: StationsRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  StationTokenRoute: StationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
