export { registerAuthCommands } from "./auth/index.js"
export { registerStationsCommands } from "./stations/index.js"
export { registerPlaylistCommands } from "./playlist/index.js"
export { registerConfigCommands } from "./config/index.js"
export { registerSearchCommand } from "./search/index.js"
export { registerBookmarksCommands } from "./bookmarks/index.js"
export { registerAccountCommands } from "./account/index.js"
export { registerTrackCommands } from "./track/index.js"
