[package]
name = "pyxis"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pyxis"
path = "src/main.rs"

[lib]
name = "pyxis"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
typeshare = "1"

[dev-dependencies]
